### ISSUE TITLE
http://localhost:4200

### ISSUE THREAD

**Issue by DevJoseWeb** [Ismaestro/angular6-example-app#30]
I'm trying to make your project run with Spring Boot API Madly, but I'm getting this error. Do you think it's CORS?

ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[CompanyComponent -> CompanyService]: 
  StaticInjectorError(Platform: core)[CompanyComponent -> CompanyService]: 
    NullInjectorError: No provider for CompanyService!
Error: StaticInjectorError(AppModule)[CompanyComponent -> CompanyService]: 
  StaticInjectorError(Platform: core)[CompanyComponent -> CompanyService]: 
    NullInjectorError: No provider for CompanyService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at

**Comment by omurbekjk** [comment]
@DevJoseWeb I think you did not add your service to app modules providers section

**Comment by DevJoseWeb** [comment]
I give up, Material is very bureaucratic, I'm using BootStrap, it got better simpler! thank you anyway !
https://github.com/DevJoseWeb/SIMPLUS
