### ISSUE TITLE
Is it possible to post from Angular to Twitter?

### ISSUE THREAD

**Issue by ziagithub2018** [Ismaestro/angular6-example-app#32]
Hi all
I want to post to twitter from Angular I don't know is this possible or not, I seen requests from node to Twitter but not from Angular,
if anyone knows please help me.

### Versions.

angular version: `6`.
node version: `8.11.2` 

npm version: `5.6`.
 Windows `10`

**Comment by Ismaestro** [comment]
Read [this](https://www.sitepoint.com/building-twitter-app-using-angular/)

:)
